name: TownyPlus
version: 1.3.0
main: townyplus.TownyPlus
author: spathwalker
softdepend: [PermissionsEx]
commands:
  tc:
    description: Enables/disables town chat.
  nc:
    description: Enables/disables nation chat.
  live:
    description: (Town) Lists online players or town players.
  tag:
    description: see /tag ?
