name: TownyPlus
version: 1.1.1
main: townyplus.TownyPlus
author: spathwalker
commands:
  tc:
    description: Enables/disables town chat.
  nc:
    description: Enables/disables nation chat.
  live:
    description: (Town) Lists online players or town players.
  tag:
    description: see /tag ?
