name: TownyPlus
version: 2.0.0
main: townyplus.Main
author: spathwalker
softdepend: [PermissionsEx]
commands:
  townyplus:
    description: see /townyplus ?
  tax:
    description: see /tax ?
  tc:
    description: Enables/disables town chat.
  nc:
    description: Enables/disables nation chat.
  live:
    description: (Town) Lists online players or town players.
  tag:
    description: see /tag ?
